model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  layer_order: bcr
  f_maps: [32, 64, 128, 256]
  num_groups: 1
  final_sigmoid: true
  is_segmentation: true

trainer:
  checkpoint_dir: CHECKPOINT_DIR_30_250_250_20_10_10
  resume: null
  pre_trained: null
  validate_after_iters: 100
  log_after_iters: 25
  max_num_epochs: 200
  max_num_iterations: 20000
  eval_score_higher_is_better: True
loss:
  name: DiceLoss
  skip_last_target: false

optimizer:
  learning_rate: 0.001
  weight_decay: 0.00001

eval_metric:
  name: MeanIoU
  thresholds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  metric: 'ap'

lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.05
  patience: 8

loaders:
  dataset: StandardHDF5Dataset
  batch_size: 4
  num_workers: 8
  raw_internal_path: X
  label_internal_path: y
  weight_internal_path: null
  train:
    file_paths:
      - ../../Datasets/3D_unique/3D_train.h5

    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [30, 250, 250]
      stride_shape: [20, 100, 100]
      threshold: 0.0
      slack_acceptance: 0.01

    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: BlobsToMask
          append_label: false
          boundary: false
        - name: ToTensor
          expand_dims: false

  val:
    file_paths:
      - ../../Datasets/3D_unique/3D_valid.h5

    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [30, 250, 250]
      stride_shape: [20, 100, 100]
      threshold: 0.0
      slack_acceptance: 1

    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: BlobsToMask
          append_label: false
          boundary: false
        - name: ToTensor
          expand_dims: false
